spring.application.name=submission-service

server.port=${SERVER_PORT:8001}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

test.service.url=${JUDGING_SERVICE_URL:localhost:8002}
auth.service.url=${AUTH_SERVICE_URL:localhost:8005}
problem.service.url=${PROBLEM_SERVICE_URL:localhost:8000}

solution.submitted.event.topic=solution-submitted-event-topic
standings.update.event.topic=standings-update-event-topic

consumer.group_id=submission-service

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.IntegerSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


