spring.application.name=problemService

server.port=${SERVER_PORT:8000}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}
consumer.group_id=problem-contest-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

test.service.url=${JUDGING_SERVICE_URL:localhost:8002}
auth.service.url=${AUTH_SERVICE_URL:localhost:8005}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=validate

server.tomcat.max-part-count=1000
server.tomcat.max-part-header-size=2048
spring.data.redis.host=${REDIS_URL:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
springdoc.api-docs.path=/api-docs

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/db.changelog-master.xml


#spring.servlet.multipart.max-files-count=100
#
#spring.servlet.multipart.max-request-size=100MB
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.enabled=true
#
#server.tomcat.max-swallow-size=100MB
#server.tomcat.connection-timeout=30000